# Generated by Django 4.0.2 on 2022-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('개봉', '개봉'), ('미개봉 및 제작중', '미개봉 및 제작중')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('뮤지컬', '뮤지컬'), ('애니메이션', '애니메이션'), ('범죄', '범죄'), ('다큐멘터리', '다큐멘터리'), ('공포(호러)', '공포(호러)'), ('미스터리', '미스터리'), ('성인물(에로)', '성인물(에로)'), ('멜로/로맨스', '멜로/로맨스'), ('코미디', '코미디'), ('SF', 'SF'), ('판타지', '판타지'), ('액션', '액션'), ('드라마', '드라마'), ('전쟁', '전쟁'), ('스릴러', '스릴러'), ('사극', '사극'), ('가족', '가족')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여자', '여자'), ('남자', '남자')], max_length=20, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.TextField(default='/static/img/user1.PNG', verbose_name='유저사진'),
        ),
    ]
