# Generated by Django 4.0.1 on 2022-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('미스터리', '미스터리'), ('성인물(에로)', '성인물(에로)'), ('사극', '사극'), ('스릴러', '스릴러'), ('SF', 'SF'), ('드라마', '드라마'), ('애니메이션', '애니메이션'), ('가족', '가족'), ('액션', '액션'), ('다큐멘터리', '다큐멘터리'), ('전쟁', '전쟁'), ('코미디', '코미디'), ('멜로/로맨스', '멜로/로맨스'), ('범죄', '범죄'), ('판타지', '판타지'), ('뮤지컬', '뮤지컬'), ('공포(호러)', '공포(호러)')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('일반 사용자', '일반 사용자'), ('제작사', '제작사')], max_length=20, verbose_name='가입 유형'),
        ),
    ]
