# Generated by Django 3.2.12 on 2022-02-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpreview',
            name='likes_user',
        ),
        migrations.AddField(
            model_name='commentpreview',
            name='like',
            field=models.IntegerField(default=0, verbose_name='좋아요'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('개봉', '개봉'), ('미개봉 및 제작중', '미개봉 및 제작중')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('코미디', '코미디'), ('스릴러', '스릴러'), ('멜로/로맨스', '멜로/로맨스'), ('공포(호러)', '공포(호러)'), ('미스터리', '미스터리'), ('SF', 'SF'), ('판타지', '판타지'), ('다큐멘터리', '다큐멘터리'), ('액션', '액션'), ('사극', '사극'), ('전쟁', '전쟁'), ('뮤지컬', '뮤지컬'), ('가족', '가족'), ('드라마', '드라마'), ('성인물(에로)', '성인물(에로)'), ('범죄', '범죄'), ('애니메이션', '애니메이션')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여자', '여자'), ('남자', '남자')], max_length=20, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('일반 사용자', '일반 사용자'), ('제작사', '제작사')], max_length=20, verbose_name='가입 유형'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.FileField(default='imgs/4.PNG', upload_to='', verbose_name='유저사진'),
        ),
    ]
