# Generated by Django 3.2.12 on 2022-02-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('범죄', '범죄'), ('드라마', '드라마'), ('멜로/로맨스', '멜로/로맨스'), ('공포(호러)', '공포(호러)'), ('미스터리', '미스터리'), ('SF', 'SF'), ('전쟁', '전쟁'), ('스릴러', '스릴러'), ('뮤지컬', '뮤지컬'), ('코미디', '코미디'), ('사극', '사극'), ('판타지', '판타지'), ('다큐멘터리', '다큐멘터리'), ('가족', '가족'), ('애니메이션', '애니메이션'), ('성인물(에로)', '성인물(에로)')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('일반 사용자', '일반 사용자'), ('제작사', '제작사')], max_length=20, verbose_name='가입 유형'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.FileField(upload_to='poster/a.jpg', verbose_name='유저사진'),
        ),
    ]
