# Generated by Django 3.2.12 on 2022-02-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('애니메이션', '애니메이션'), ('공포(호러)', '공포(호러)'), ('액션', '액션'), ('스릴러', '스릴러'), ('성인물(에로)', '성인물(에로)'), ('뮤지컬', '뮤지컬'), ('사극', '사극'), ('가족', '가족'), ('코미디', '코미디'), ('판타지', '판타지'), ('드라마', '드라마'), ('SF', 'SF'), ('전쟁', '전쟁'), ('미스터리', '미스터리'), ('다큐멘터리', '다큐멘터리'), ('범죄', '범죄'), ('멜로/로맨스', '멜로/로맨스')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여자', '여자'), ('남자', '남자')], max_length=20, verbose_name='성별'),
        ),
    ]
