# Generated by Django 4.0.1 on 2022-02-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('미개봉 및 제작중', '미개봉 및 제작중'), ('개봉', '개봉')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('범죄', '범죄'), ('사극', '사극'), ('공포(호러)', '공포(호러)'), ('다큐멘터리', '다큐멘터리'), ('가족', '가족'), ('스릴러', '스릴러'), ('뮤지컬', '뮤지컬'), ('애니메이션', '애니메이션'), ('코미디', '코미디'), ('SF', 'SF'), ('액션', '액션'), ('멜로/로맨스', '멜로/로맨스'), ('드라마', '드라마'), ('판타지', '판타지'), ('미스터리', '미스터리'), ('전쟁', '전쟁'), ('성인물(에로)', '성인물(에로)')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.TextField(default='/static/img/user4.PNG', verbose_name='유저사진'),
        ),
    ]
