# Generated by Django 3.2.12 on 2022-02-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_remove_unreleasedmovie_intro_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('genre', models.CharField(choices=[('전쟁', '전쟁'), ('애니메이션', '애니메이션'), ('액션', '액션'), ('드라마', '드라마'), ('공포(호러)', '공포(호러)'), ('성인물(에로)', '성인물(에로)'), ('SF', 'SF'), ('미스터리', '미스터리'), ('사극', '사극'), ('코미디', '코미디'), ('멜로/로맨스', '멜로/로맨스'), ('범죄', '범죄'), ('뮤지컬', '뮤지컬'), ('다큐멘터리', '다큐멘터리'), ('판타지', '판타지'), ('스릴러', '스릴러'), ('가족', '가족')], max_length=100, verbose_name='장르')),
                ('running_time', models.IntegerField(null=True, verbose_name='러닝타임')),
                ('release_date', models.DateField(verbose_name='개봉')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('actor', models.CharField(max_length=100, verbose_name='배우')),
                ('content', models.TextField(null=True, verbose_name='개요')),
                ('rating', models.FloatField(default=0, verbose_name='평점')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='포스터')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='예고편')),
                ('url', models.URLField(null=True, verbose_name='링크')),
                ('comeout', models.CharField(choices=[('개봉', '개봉'), ('미개봉 및 제작중', '미개봉 및 제작중')], max_length=100, verbose_name='개봉여부')),
            ],
        ),
        migrations.RemoveField(
            model_name='unreleasedmovie',
            name='user',
        ),
        migrations.AlterField(
            model_name='commentpreview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.movie'),
        ),
        migrations.DeleteModel(
            name='ReleasedMovie',
        ),
        migrations.DeleteModel(
            name='UnreleasedMovie',
        ),
    ]
