# Generated by Django 3.2.11 on 2022-02-13 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_auto_20220212_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpreview',
            name='like',
        ),
        migrations.AddField(
            model_name='commentpreview',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('개봉', '개봉'), ('미개봉 및 제작중', '미개봉 및 제작중')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('가족', '가족'), ('코미디', '코미디'), ('공포(호러)', '공포(호러)'), ('드라마', '드라마'), ('스릴러', '스릴러'), ('범죄', '범죄'), ('미스터리', '미스터리'), ('성인물(에로)', '성인물(에로)'), ('사극', '사극'), ('판타지', '판타지'), ('전쟁', '전쟁'), ('뮤지컬', '뮤지컬'), ('SF', 'SF'), ('액션', '액션'), ('멜로/로맨스', '멜로/로맨스'), ('애니메이션', '애니메이션'), ('다큐멘터리', '다큐멘터리')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('일반 사용자', '일반 사용자'), ('제작사', '제작사')], max_length=20, verbose_name='가입 유형'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.FileField(default='imgs/4.PNG', upload_to='', verbose_name='유저사진'),
        ),
    ]
