# Generated by Django 4.0.1 on 2022-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_alter_movie_genre_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('미개봉 및 제작중', '미개봉 및 제작중'), ('개봉', '개봉')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('드라마', '드라마'), ('가족', '가족'), ('코미디', '코미디'), ('성인물(에로)', '성인물(에로)'), ('범죄', '범죄'), ('다큐멘터리', '다큐멘터리'), ('액션', '액션'), ('판타지', '판타지'), ('멜로/로맨스', '멜로/로맨스'), ('공포(호러)', '공포(호러)'), ('미스터리', '미스터리'), ('뮤지컬', '뮤지컬'), ('스릴러', '스릴러'), ('전쟁', '전쟁'), ('애니메이션', '애니메이션'), ('사극', '사극')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('제작사', '제작사'), ('일반 사용자', '일반 사용자')], max_length=20, verbose_name='가입 유형'),
        ),
    ]
