# Generated by Django 4.0.1 on 2022-02-05 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_remove_unreleasedmovie_intro_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedmovie',
            name='genre',
            field=models.CharField(choices=[('공포(호러)', '공포(호러)'), ('드라마', '드라마'), ('판타지', '판타지'), ('성인물(에로)', '성인물(에로)'), ('뮤지컬', '뮤지컬'), ('다큐멘터리', '다큐멘터리'), ('멜로/로맨스', '멜로/로맨스'), ('SF', 'SF'), ('코미디', '코미디'), ('사극', '사극'), ('액션', '액션'), ('애니메이션', '애니메이션'), ('전쟁', '전쟁'), ('범죄', '범죄'), ('미스터리', '미스터리'), ('가족', '가족'), ('스릴러', '스릴러')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='releasedmovie',
            name='grade',
            field=models.CharField(choices=[('12세', '12세'), ('청소년 관람불가', '청소년 관람불가'), ('15세', '15세'), ('전체 관람가', '전체 관람가')], max_length=20, verbose_name='등급'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, verbose_name='한 줄 제목'),
        ),
        migrations.AlterField(
            model_name='unreleasedmovie',
            name='genre',
            field=models.CharField(choices=[('공포(호러)', '공포(호러)'), ('드라마', '드라마'), ('판타지', '판타지'), ('성인물(에로)', '성인물(에로)'), ('뮤지컬', '뮤지컬'), ('다큐멘터리', '다큐멘터리'), ('멜로/로맨스', '멜로/로맨스'), ('SF', 'SF'), ('코미디', '코미디'), ('사극', '사극'), ('액션', '액션'), ('애니메이션', '애니메이션'), ('전쟁', '전쟁'), ('범죄', '범죄'), ('미스터리', '미스터리'), ('가족', '가족'), ('스릴러', '스릴러')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='unreleasedmovie',
            name='grade',
            field=models.CharField(blank=True, choices=[('12세', '12세'), ('청소년 관람불가', '청소년 관람불가'), ('15세', '15세'), ('전체 관람가', '전체 관람가')], max_length=20, null=True, verbose_name='등급'),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('hits', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
