# Generated by Django 4.0.2 on 2022-02-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_remove_unreleasedmovie_intro_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedmovie',
            name='genre',
            field=models.CharField(choices=[('멜로/로맨스', '멜로/로맨스'), ('사극', '사극'), ('가족', '가족'), ('다큐멘터리', '다큐멘터리'), ('애니메이션', '애니메이션'), ('액션', '액션'), ('범죄', '범죄'), ('뮤지컬', '뮤지컬'), ('성인물(에로)', '성인물(에로)'), ('전쟁', '전쟁'), ('판타지', '판타지'), ('SF', 'SF'), ('드라마', '드라마'), ('스릴러', '스릴러'), ('공포(호러)', '공포(호러)'), ('코미디', '코미디'), ('미스터리', '미스터리')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='releasedmovie',
            name='grade',
            field=models.CharField(choices=[('15세', '15세'), ('전체 관람가', '전체 관람가'), ('청소년 관람불가', '청소년 관람불가'), ('12세', '12세')], max_length=20, verbose_name='등급'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, verbose_name='한 줄 제목'),
        ),
        migrations.AlterField(
            model_name='unreleasedmovie',
            name='genre',
            field=models.CharField(choices=[('멜로/로맨스', '멜로/로맨스'), ('사극', '사극'), ('가족', '가족'), ('다큐멘터리', '다큐멘터리'), ('애니메이션', '애니메이션'), ('액션', '액션'), ('범죄', '범죄'), ('뮤지컬', '뮤지컬'), ('성인물(에로)', '성인물(에로)'), ('전쟁', '전쟁'), ('판타지', '판타지'), ('SF', 'SF'), ('드라마', '드라마'), ('스릴러', '스릴러'), ('공포(호러)', '공포(호러)'), ('코미디', '코미디'), ('미스터리', '미스터리')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='unreleasedmovie',
            name='grade',
            field=models.CharField(blank=True, choices=[('15세', '15세'), ('전체 관람가', '전체 관람가'), ('청소년 관람불가', '청소년 관람불가'), ('12세', '12세')], max_length=20, null=True, verbose_name='등급'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여자', '여자'), ('남자', '남자')], max_length=20, verbose_name='성별'),
        ),
    ]
