# Generated by Django 3.2.11 on 2022-02-13 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_auto_20220213_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='commentpreview',
            name='like',
        ),
        migrations.AddField(
            model_name='commentpreview',
            name='like',
            field=models.IntegerField(default=0, verbose_name='좋아요'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('미개봉 및 제작중', '미개봉 및 제작중'), ('개봉', '개봉')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('범죄', '범죄'), ('공포(호러)', '공포(호러)'), ('코미디', '코미디'), ('액션', '액션'), ('애니메이션', '애니메이션'), ('SF', 'SF'), ('판타지', '판타지'), ('다큐멘터리', '다큐멘터리'), ('미스터리', '미스터리'), ('성인물(에로)', '성인물(에로)'), ('가족', '가족'), ('뮤지컬', '뮤지컬'), ('멜로/로맨스', '멜로/로맨스'), ('전쟁', '전쟁'), ('드라마', '드라마'), ('사극', '사극'), ('스릴러', '스릴러')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=20, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('제작사', '제작사'), ('일반 사용자', '일반 사용자')], max_length=20, verbose_name='가입 유형'),
        ),
    ]
