# Generated by Django 3.2.12 on 2022-02-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_auto_20220210_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('판타지', '판타지'), ('가족', '가족'), ('코미디', '코미디'), ('스릴러', '스릴러'), ('공포(호러)', '공포(호러)'), ('성인물(에로)', '성인물(에로)'), ('사극', '사극'), ('뮤지컬', '뮤지컬'), ('액션', '액션'), ('드라마', '드라마'), ('애니메이션', '애니메이션'), ('멜로/로맨스', '멜로/로맨스'), ('미스터리', '미스터리'), ('전쟁', '전쟁'), ('SF', 'SF'), ('다큐멘터리', '다큐멘터리'), ('범죄', '범죄')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=20, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.FileField(default='imgs/3.PNG', upload_to='', verbose_name='유저사진'),
        ),
    ]
