# Generated by Django 4.0.1 on 2022-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_movie_remove_unreleasedmovie_user_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='포스터'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('개봉', '개봉'), ('미개봉 및 제작중', '미개봉 및 제작중')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('사극', '사극'), ('다큐멘터리', '다큐멘터리'), ('드라마', '드라마'), ('액션', '액션'), ('스릴러', '스릴러'), ('코미디', '코미디'), ('미스터리', '미스터리'), ('멜로/로맨스', '멜로/로맨스'), ('판타지', '판타지'), ('가족', '가족'), ('애니메이션', '애니메이션'), ('SF', 'SF'), ('성인물(에로)', '성인물(에로)'), ('전쟁', '전쟁'), ('뮤지컬', '뮤지컬'), ('범죄', '범죄'), ('공포(호러)', '공포(호러)')], max_length=100, verbose_name='장르'),
        ),
    ]
