# Generated by Django 4.0.2 on 2022-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_alter_movie_genre_alter_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('미개봉 및 제작중', '미개봉 및 제작중'), ('개봉', '개봉')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('스릴러', '스릴러'), ('범죄', '범죄'), ('다큐멘터리', '다큐멘터리'), ('사극', '사극'), ('미스터리', '미스터리'), ('멜로/로맨스', '멜로/로맨스'), ('공포(호러)', '공포(호러)'), ('전쟁', '전쟁'), ('코미디', '코미디'), ('애니메이션', '애니메이션'), ('성인물(에로)', '성인물(에로)'), ('뮤지컬', '뮤지컬'), ('SF', 'SF'), ('드라마', '드라마'), ('가족', '가족'), ('판타지', '판타지')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=20, verbose_name='성별'),
        ),
    ]
