# Generated by Django 4.0.2 on 2022-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_alter_movie_comeout_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('범죄', '범죄'), ('SF', 'SF'), ('사극', '사극'), ('판타지', '판타지'), ('애니메이션', '애니메이션'), ('가족', '가족'), ('미스터리', '미스터리'), ('다큐멘터리', '다큐멘터리'), ('멜로/로맨스', '멜로/로맨스'), ('코미디', '코미디'), ('공포(호러)', '공포(호러)'), ('뮤지컬', '뮤지컬'), ('전쟁', '전쟁'), ('성인물(에로)', '성인물(에로)'), ('드라마', '드라마'), ('스릴러', '스릴러')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('제작사', '제작사'), ('일반 사용자', '일반 사용자')], max_length=20, verbose_name='가입 유형'),
        ),
    ]
