# Generated by Django 4.0.1 on 2022-02-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_alter_releasedmovie_genre_alter_releasedmovie_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedmovie',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('미스터리', '미스터리'), ('성인물(에로)', '성인물(에로)'), ('가족', '가족'), ('드라마', '드라마'), ('멜로/로맨스', '멜로/로맨스'), ('애니메이션', '애니메이션'), ('액션', '액션'), ('사극', '사극'), ('전쟁', '전쟁'), ('뮤지컬', '뮤지컬'), ('판타지', '판타지'), ('범죄', '범죄'), ('공포(호러)', '공포(호러)'), ('코미디', '코미디'), ('다큐멘터리', '다큐멘터리'), ('스릴러', '스릴러')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='releasedmovie',
            name='grade',
            field=models.CharField(choices=[('전체 관람가', '전체 관람가'), ('청소년 관람불가', '청소년 관람불가'), ('12세', '12세'), ('15세', '15세')], max_length=20, verbose_name='등급'),
        ),
        migrations.AlterField(
            model_name='unreleasedmovie',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('미스터리', '미스터리'), ('성인물(에로)', '성인물(에로)'), ('가족', '가족'), ('드라마', '드라마'), ('멜로/로맨스', '멜로/로맨스'), ('애니메이션', '애니메이션'), ('액션', '액션'), ('사극', '사극'), ('전쟁', '전쟁'), ('뮤지컬', '뮤지컬'), ('판타지', '판타지'), ('범죄', '범죄'), ('공포(호러)', '공포(호러)'), ('코미디', '코미디'), ('다큐멘터리', '다큐멘터리'), ('스릴러', '스릴러')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='unreleasedmovie',
            name='grade',
            field=models.CharField(blank=True, choices=[('전체 관람가', '전체 관람가'), ('청소년 관람불가', '청소년 관람불가'), ('12세', '12세'), ('15세', '15세')], max_length=20, null=True, verbose_name='등급'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여자', '여자'), ('남자', '남자')], max_length=20, verbose_name='성별'),
        ),
    ]
