# Generated by Django 4.0.1 on 2022-02-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_auto_20220206_2140'),
        ('theater', '0005_alter_releasedmovie_genre_alter_releasedmovie_grade_and_more'),
    ]

    operations = [
    ]
