# Generated by Django 4.0.1 on 2022-02-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0006_alter_movie_genre_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comeout',
            field=models.CharField(choices=[('개봉', '개봉'), ('미개봉 및 제작중', '미개봉 및 제작중')], max_length=100, verbose_name='개봉여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('스릴러', '스릴러'), ('액션', '액션'), ('SF', 'SF'), ('멜로/로맨스', '멜로/로맨스'), ('드라마', '드라마'), ('다큐멘터리', '다큐멘터리'), ('범죄', '범죄'), ('애니메이션', '애니메이션'), ('성인물(에로)', '성인물(에로)'), ('전쟁', '전쟁'), ('사극', '사극'), ('판타지', '판타지'), ('코미디', '코미디'), ('미스터리', '미스터리'), ('공포(호러)', '공포(호러)'), ('뮤지컬', '뮤지컬'), ('가족', '가족')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('일반 사용자', '일반 사용자'), ('제작사', '제작사')], max_length=20, verbose_name='가입 유형'),
        ),
    ]
